[2020-03-16T13:01:33+00:00][error] {"message":"SQLSTATE[08006] [7] FATAL:  could not open relation mapping file \"global\/pg_filenode.map\": No such file or directory","trace":"#0 [internal function]: PDO->__construct('pgsql:host=mooc...', 'postgres', 'root', Array)\n#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->connect(Array)\n#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\Postgresql->connect(Array)\n#3 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->__construct(Array)\n#4 \/var\/www\/html\/app\/config\/services.php(82): Phalcon\\Db\\Adapter\\Pdo\\Postgresql->__construct(Array)\n#5 [internal function]: Closure->{closure}()\n#6 [internal function]: Phalcon\\Di\\Service->resolve(NULL, Object(Phalcon\\Di\\FactoryDefault))\n#7 [internal function]: Phalcon\\Di->get('db', NULL)\n#8 [internal function]: Phalcon\\Di->getShared('db')\n#9 [internal function]: Phalcon\\Mvc\\Model\\Manager->_getConnection(Object(NovaMooc\\Models\\Users), Array)\n#10 [internal function]: Phalcon\\Mvc\\Model\\Manager->getReadConnection(Object(NovaMooc\\Models\\Users))\n#11 [internal function]: Phalcon\\Mvc\\Model->getReadConnection()\n#12 [internal function]: Phalcon\\Mvc\\Model\\MetaData\\Strategy\\Introspection->getMetaData(Object(NovaMooc\\Models\\Users), Object(Phalcon\\Di\\FactoryDefault))\n#13 [internal function]: Phalcon\\Mvc\\Model\\MetaData->initialize(Object(NovaMooc\\Models\\Users), 'novamooc\\\\models...', 'nov_users', 'public')\n#14 [internal function]: Phalcon\\Mvc\\Model\\MetaData->readMetaData(Object(NovaMooc\\Models\\Users))\n#15 [internal function]: Phalcon\\Mvc\\Model\\MetaData->hasAttribute(Object(NovaMooc\\Models\\Users), 'email')\n#16 [internal function]: Phalcon\\Mvc\\Model\\Query->_getQualified(Array)\n#17 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#18 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#19 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array)\n#20 [internal function]: Phalcon\\Mvc\\Model\\Query->_prepareSelect()\n#21 [internal function]: Phalcon\\Mvc\\Model\\Query->parse()\n#22 [internal function]: Phalcon\\Mvc\\Model\\Query->execute()\n#23 \/var\/www\/html\/app\/models\/Users.php(95): Phalcon\\Mvc\\Model::findFirst(Array)\n#24 \/var\/www\/html\/app\/controllers\/IndexController.php(32): NovaMooc\\Models\\Users::findFirst(Array)\n#25 [internal function]: IndexController->loginAction()\n#26 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(IndexController), 'loginAction', Array)\n#27 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#28 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/login')\n#29 {main}"}
[2020-03-16T13:01:39+00:00][error] {"message":"SQLSTATE[08006] [7] FATAL:  could not open relation mapping file \"global\/pg_filenode.map\": No such file or directory","trace":"#0 [internal function]: PDO->__construct('pgsql:host=mooc...', 'postgres', 'root', Array)\n#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->connect(Array)\n#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\Postgresql->connect(Array)\n#3 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->__construct(Array)\n#4 \/var\/www\/html\/app\/config\/services.php(82): Phalcon\\Db\\Adapter\\Pdo\\Postgresql->__construct(Array)\n#5 [internal function]: Closure->{closure}()\n#6 [internal function]: Phalcon\\Di\\Service->resolve(NULL, Object(Phalcon\\Di\\FactoryDefault))\n#7 [internal function]: Phalcon\\Di->get('db', NULL)\n#8 [internal function]: Phalcon\\Di->getShared('db')\n#9 [internal function]: Phalcon\\Mvc\\Model\\Manager->_getConnection(Object(NovaMooc\\Models\\Users), Array)\n#10 [internal function]: Phalcon\\Mvc\\Model\\Manager->getReadConnection(Object(NovaMooc\\Models\\Users))\n#11 [internal function]: Phalcon\\Mvc\\Model->getReadConnection()\n#12 [internal function]: Phalcon\\Mvc\\Model\\MetaData\\Strategy\\Introspection->getMetaData(Object(NovaMooc\\Models\\Users), Object(Phalcon\\Di\\FactoryDefault))\n#13 [internal function]: Phalcon\\Mvc\\Model\\MetaData->initialize(Object(NovaMooc\\Models\\Users), 'novamooc\\\\models...', 'nov_users', 'public')\n#14 [internal function]: Phalcon\\Mvc\\Model\\MetaData->readMetaData(Object(NovaMooc\\Models\\Users))\n#15 [internal function]: Phalcon\\Mvc\\Model\\MetaData->hasAttribute(Object(NovaMooc\\Models\\Users), 'email')\n#16 [internal function]: Phalcon\\Mvc\\Model\\Query->_getQualified(Array)\n#17 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#18 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#19 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array)\n#20 [internal function]: Phalcon\\Mvc\\Model\\Query->_prepareSelect()\n#21 [internal function]: Phalcon\\Mvc\\Model\\Query->parse()\n#22 [internal function]: Phalcon\\Mvc\\Model\\Query->execute()\n#23 \/var\/www\/html\/app\/models\/Users.php(95): Phalcon\\Mvc\\Model::findFirst(Array)\n#24 \/var\/www\/html\/app\/controllers\/IndexController.php(32): NovaMooc\\Models\\Users::findFirst(Array)\n#25 [internal function]: IndexController->loginAction()\n#26 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(IndexController), 'loginAction', Array)\n#27 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#28 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/login')\n#29 {main}"}
[2020-03-16T13:01:43+00:00][error] {"message":"SQLSTATE[08006] [7] FATAL:  could not open relation mapping file \"global\/pg_filenode.map\": No such file or directory","trace":"#0 [internal function]: PDO->__construct('pgsql:host=mooc...', 'postgres', 'root', Array)\n#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->connect(Array)\n#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\Postgresql->connect(Array)\n#3 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->__construct(Array)\n#4 \/var\/www\/html\/app\/config\/services.php(82): Phalcon\\Db\\Adapter\\Pdo\\Postgresql->__construct(Array)\n#5 [internal function]: Closure->{closure}()\n#6 [internal function]: Phalcon\\Di\\Service->resolve(NULL, Object(Phalcon\\Di\\FactoryDefault))\n#7 [internal function]: Phalcon\\Di->get('db', NULL)\n#8 [internal function]: Phalcon\\Di->getShared('db')\n#9 [internal function]: Phalcon\\Mvc\\Model\\Manager->_getConnection(Object(NovaMooc\\Models\\Users), Array)\n#10 [internal function]: Phalcon\\Mvc\\Model\\Manager->getReadConnection(Object(NovaMooc\\Models\\Users))\n#11 [internal function]: Phalcon\\Mvc\\Model->getReadConnection()\n#12 [internal function]: Phalcon\\Mvc\\Model\\MetaData\\Strategy\\Introspection->getMetaData(Object(NovaMooc\\Models\\Users), Object(Phalcon\\Di\\FactoryDefault))\n#13 [internal function]: Phalcon\\Mvc\\Model\\MetaData->initialize(Object(NovaMooc\\Models\\Users), 'novamooc\\\\models...', 'nov_users', 'public')\n#14 [internal function]: Phalcon\\Mvc\\Model\\MetaData->readMetaData(Object(NovaMooc\\Models\\Users))\n#15 [internal function]: Phalcon\\Mvc\\Model\\MetaData->hasAttribute(Object(NovaMooc\\Models\\Users), 'email')\n#16 [internal function]: Phalcon\\Mvc\\Model\\Query->_getQualified(Array)\n#17 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#18 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#19 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array)\n#20 [internal function]: Phalcon\\Mvc\\Model\\Query->_prepareSelect()\n#21 [internal function]: Phalcon\\Mvc\\Model\\Query->parse()\n#22 [internal function]: Phalcon\\Mvc\\Model\\Query->execute()\n#23 \/var\/www\/html\/app\/models\/Users.php(95): Phalcon\\Mvc\\Model::findFirst(Array)\n#24 \/var\/www\/html\/app\/controllers\/IndexController.php(32): NovaMooc\\Models\\Users::findFirst(Array)\n#25 [internal function]: IndexController->loginAction()\n#26 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(IndexController), 'loginAction', Array)\n#27 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#28 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/login')\n#29 {main}"}
[2020-03-16T13:02:15+00:00][error] {"message":"SQLSTATE[08006] [7] server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.","trace":"#0 [internal function]: PDO->__construct('pgsql:host=mooc...', 'postgres', 'root', Array)\n#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->connect(Array)\n#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\Postgresql->connect(Array)\n#3 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->__construct(Array)\n#4 \/var\/www\/html\/app\/config\/services.php(82): Phalcon\\Db\\Adapter\\Pdo\\Postgresql->__construct(Array)\n#5 [internal function]: Closure->{closure}()\n#6 [internal function]: Phalcon\\Di\\Service->resolve(NULL, Object(Phalcon\\Di\\FactoryDefault))\n#7 [internal function]: Phalcon\\Di->get('db', NULL)\n#8 [internal function]: Phalcon\\Di->getShared('db')\n#9 [internal function]: Phalcon\\Mvc\\Model\\Manager->_getConnection(Object(NovaMooc\\Models\\Users), Array)\n#10 [internal function]: Phalcon\\Mvc\\Model\\Manager->getReadConnection(Object(NovaMooc\\Models\\Users))\n#11 [internal function]: Phalcon\\Mvc\\Model->getReadConnection()\n#12 [internal function]: Phalcon\\Mvc\\Model\\MetaData\\Strategy\\Introspection->getMetaData(Object(NovaMooc\\Models\\Users), Object(Phalcon\\Di\\FactoryDefault))\n#13 [internal function]: Phalcon\\Mvc\\Model\\MetaData->initialize(Object(NovaMooc\\Models\\Users), 'novamooc\\\\models...', 'nov_users', 'public')\n#14 [internal function]: Phalcon\\Mvc\\Model\\MetaData->readMetaData(Object(NovaMooc\\Models\\Users))\n#15 [internal function]: Phalcon\\Mvc\\Model\\MetaData->hasAttribute(Object(NovaMooc\\Models\\Users), 'email')\n#16 [internal function]: Phalcon\\Mvc\\Model\\Query->_getQualified(Array)\n#17 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#18 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#19 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array)\n#20 [internal function]: Phalcon\\Mvc\\Model\\Query->_prepareSelect()\n#21 [internal function]: Phalcon\\Mvc\\Model\\Query->parse()\n#22 [internal function]: Phalcon\\Mvc\\Model\\Query->execute()\n#23 \/var\/www\/html\/app\/models\/Users.php(95): Phalcon\\Mvc\\Model::findFirst(Array)\n#24 \/var\/www\/html\/app\/controllers\/IndexController.php(32): NovaMooc\\Models\\Users::findFirst(Array)\n#25 [internal function]: IndexController->loginAction()\n#26 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(IndexController), 'loginAction', Array)\n#27 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#28 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/login')\n#29 {main}"}
[2020-03-16T13:02:28+00:00][error] {"message":"SQLSTATE[08006] [7] could not translate host name \"mooc-db\" to address: No address associated with hostname","trace":"#0 [internal function]: PDO->__construct('pgsql:host=mooc...', 'postgres', 'root', Array)\n#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->connect(Array)\n#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\Postgresql->connect(Array)\n#3 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->__construct(Array)\n#4 \/var\/www\/html\/app\/config\/services.php(82): Phalcon\\Db\\Adapter\\Pdo\\Postgresql->__construct(Array)\n#5 [internal function]: Closure->{closure}()\n#6 [internal function]: Phalcon\\Di\\Service->resolve(NULL, Object(Phalcon\\Di\\FactoryDefault))\n#7 [internal function]: Phalcon\\Di->get('db', NULL)\n#8 [internal function]: Phalcon\\Di->getShared('db')\n#9 [internal function]: Phalcon\\Mvc\\Model\\Manager->_getConnection(Object(NovaMooc\\Models\\Users), Array)\n#10 [internal function]: Phalcon\\Mvc\\Model\\Manager->getReadConnection(Object(NovaMooc\\Models\\Users))\n#11 [internal function]: Phalcon\\Mvc\\Model->getReadConnection()\n#12 [internal function]: Phalcon\\Mvc\\Model\\MetaData\\Strategy\\Introspection->getMetaData(Object(NovaMooc\\Models\\Users), Object(Phalcon\\Di\\FactoryDefault))\n#13 [internal function]: Phalcon\\Mvc\\Model\\MetaData->initialize(Object(NovaMooc\\Models\\Users), 'novamooc\\\\models...', 'nov_users', 'public')\n#14 [internal function]: Phalcon\\Mvc\\Model\\MetaData->readMetaData(Object(NovaMooc\\Models\\Users))\n#15 [internal function]: Phalcon\\Mvc\\Model\\MetaData->hasAttribute(Object(NovaMooc\\Models\\Users), 'email')\n#16 [internal function]: Phalcon\\Mvc\\Model\\Query->_getQualified(Array)\n#17 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#18 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#19 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array)\n#20 [internal function]: Phalcon\\Mvc\\Model\\Query->_prepareSelect()\n#21 [internal function]: Phalcon\\Mvc\\Model\\Query->parse()\n#22 [internal function]: Phalcon\\Mvc\\Model\\Query->execute()\n#23 \/var\/www\/html\/app\/models\/Users.php(95): Phalcon\\Mvc\\Model::findFirst(Array)\n#24 \/var\/www\/html\/app\/controllers\/IndexController.php(32): NovaMooc\\Models\\Users::findFirst(Array)\n#25 [internal function]: IndexController->loginAction()\n#26 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(IndexController), 'loginAction', Array)\n#27 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#28 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/login')\n#29 {main}"}
[2020-03-16T13:37:43+00:00][error] {"message":"Response was already sent","trace":"#0 \/var\/www\/html\/app\/plugins\/SecurityPlugin.php(104): Phalcon\\Http\\Response->send()\n#1 [internal function]: SecurityPlugin->beforeException(Object(Phalcon\\Events\\Event), Object(Phalcon\\Mvc\\Dispatcher), Object(Phalcon\\Http\\Response\\Exception))\n#2 [internal function]: Phalcon\\Events\\Manager->fireQueue(Object(SplPriorityQueue), Object(Phalcon\\Events\\Event))\n#3 [internal function]: Phalcon\\Events\\Manager->fire('dispatch:before...', Object(Phalcon\\Mvc\\Dispatcher), Object(Phalcon\\Http\\Response\\Exception))\n#4 [internal function]: Phalcon\\Mvc\\Dispatcher->handleException(Object(Phalcon\\Http\\Response\\Exception))\n#5 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#6 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/')\n#7 {main}"}
[2020-03-16T13:37:44+00:00][error] {"message":"Response was already sent","trace":"#0 \/var\/www\/html\/app\/plugins\/SecurityPlugin.php(104): Phalcon\\Http\\Response->send()\n#1 [internal function]: SecurityPlugin->beforeException(Object(Phalcon\\Events\\Event), Object(Phalcon\\Mvc\\Dispatcher), Object(Phalcon\\Http\\Response\\Exception))\n#2 [internal function]: Phalcon\\Events\\Manager->fireQueue(Object(SplPriorityQueue), Object(Phalcon\\Events\\Event))\n#3 [internal function]: Phalcon\\Events\\Manager->fire('dispatch:before...', Object(Phalcon\\Mvc\\Dispatcher), Object(Phalcon\\Http\\Response\\Exception))\n#4 [internal function]: Phalcon\\Mvc\\Dispatcher->handleException(Object(Phalcon\\Http\\Response\\Exception))\n#5 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#6 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/')\n#7 {main}"}
[2020-03-16T13:37:45+00:00][error] {"message":"ApiDocController handler class cannot be loaded","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->throwDispatchException('ApiDocControlle...', 2)\n#1 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#2 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api_doc\/vendor...')\n#3 {main}"}
[2020-03-16T13:39:25+00:00][error] {"message":"Response was already sent","trace":"#0 \/var\/www\/html\/app\/plugins\/SecurityPlugin.php(104): Phalcon\\Http\\Response->send()\n#1 [internal function]: SecurityPlugin->beforeException(Object(Phalcon\\Events\\Event), Object(Phalcon\\Mvc\\Dispatcher), Object(Phalcon\\Http\\Response\\Exception))\n#2 [internal function]: Phalcon\\Events\\Manager->fireQueue(Object(SplPriorityQueue), Object(Phalcon\\Events\\Event))\n#3 [internal function]: Phalcon\\Events\\Manager->fire('dispatch:before...', Object(Phalcon\\Mvc\\Dispatcher), Object(Phalcon\\Http\\Response\\Exception))\n#4 [internal function]: Phalcon\\Mvc\\Dispatcher->handleException(Object(Phalcon\\Http\\Response\\Exception))\n#5 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#6 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/')\n#7 {main}"}
[2020-03-16T13:39:26+00:00][error] {"message":"Response was already sent","trace":"#0 \/var\/www\/html\/app\/plugins\/SecurityPlugin.php(104): Phalcon\\Http\\Response->send()\n#1 [internal function]: SecurityPlugin->beforeException(Object(Phalcon\\Events\\Event), Object(Phalcon\\Mvc\\Dispatcher), Object(Phalcon\\Http\\Response\\Exception))\n#2 [internal function]: Phalcon\\Events\\Manager->fireQueue(Object(SplPriorityQueue), Object(Phalcon\\Events\\Event))\n#3 [internal function]: Phalcon\\Events\\Manager->fire('dispatch:before...', Object(Phalcon\\Mvc\\Dispatcher), Object(Phalcon\\Http\\Response\\Exception))\n#4 [internal function]: Phalcon\\Mvc\\Dispatcher->handleException(Object(Phalcon\\Http\\Response\\Exception))\n#5 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#6 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/')\n#7 {main}"}
[2020-03-16T13:39:26+00:00][error] {"message":"ApiDocController handler class cannot be loaded","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->throwDispatchException('ApiDocControlle...', 2)\n#1 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#2 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api_doc\/vendor...')\n#3 {main}"}
[2020-03-16T13:40:21+00:00][error] {"message":"Response was already sent","trace":"#0 \/var\/www\/html\/app\/plugins\/SecurityPlugin.php(104): Phalcon\\Http\\Response->send()\n#1 [internal function]: SecurityPlugin->beforeException(Object(Phalcon\\Events\\Event), Object(Phalcon\\Mvc\\Dispatcher), Object(Phalcon\\Http\\Response\\Exception))\n#2 [internal function]: Phalcon\\Events\\Manager->fireQueue(Object(SplPriorityQueue), Object(Phalcon\\Events\\Event))\n#3 [internal function]: Phalcon\\Events\\Manager->fire('dispatch:before...', Object(Phalcon\\Mvc\\Dispatcher), Object(Phalcon\\Http\\Response\\Exception))\n#4 [internal function]: Phalcon\\Mvc\\Dispatcher->handleException(Object(Phalcon\\Http\\Response\\Exception))\n#5 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#6 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/')\n#7 {main}"}
[2020-03-16T13:40:22+00:00][error] {"message":"Response was already sent","trace":"#0 \/var\/www\/html\/app\/plugins\/SecurityPlugin.php(104): Phalcon\\Http\\Response->send()\n#1 [internal function]: SecurityPlugin->beforeException(Object(Phalcon\\Events\\Event), Object(Phalcon\\Mvc\\Dispatcher), Object(Phalcon\\Http\\Response\\Exception))\n#2 [internal function]: Phalcon\\Events\\Manager->fireQueue(Object(SplPriorityQueue), Object(Phalcon\\Events\\Event))\n#3 [internal function]: Phalcon\\Events\\Manager->fire('dispatch:before...', Object(Phalcon\\Mvc\\Dispatcher), Object(Phalcon\\Http\\Response\\Exception))\n#4 [internal function]: Phalcon\\Mvc\\Dispatcher->handleException(Object(Phalcon\\Http\\Response\\Exception))\n#5 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#6 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/')\n#7 {main}"}
[2020-03-16T13:40:22+00:00][error] {"message":"ApiDocController handler class cannot be loaded","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->throwDispatchException('ApiDocControlle...', 2)\n#1 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#2 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api_doc\/vendor...')\n#3 {main}"}
