[Sun, 24 Nov 19 23:20:03 +0000][error] {"message":"Utilisateur d\u00e9j\u00e0 existant","trace":"#0 [internal function]: IndexController->inscriptionAction()\n#1 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(IndexController), 'inscriptionActi...', Array)\n#2 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#3 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/inscriptio...')\n#4 {main}"}
[Sun, 24 Nov 19 23:20:09 +0000][error] {"message":"Utilisateur d\u00e9j\u00e0 existant","trace":"#0 [internal function]: IndexController->inscriptionAction()\n#1 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(IndexController), 'inscriptionActi...', Array)\n#2 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#3 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/inscriptio...')\n#4 {main}"}
[2020-03-15T16:53:44+00:00][error] {"message":"SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"mooc-db\" (172.23.0.2) and accepting\n\tTCP\/IP connections on port 5432?","trace":"#0 [internal function]: PDO->__construct('pgsql:host=mooc...', 'postgres', 'root', Array)\n#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->connect(Array)\n#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\Postgresql->connect(Array)\n#3 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->__construct(Array)\n#4 \/var\/www\/html\/app\/config\/services.php(82): Phalcon\\Db\\Adapter\\Pdo\\Postgresql->__construct(Array)\n#5 [internal function]: Closure->{closure}()\n#6 [internal function]: Phalcon\\Di\\Service->resolve(NULL, Object(Phalcon\\Di\\FactoryDefault))\n#7 [internal function]: Phalcon\\Di->get('db', NULL)\n#8 [internal function]: Phalcon\\Di->getShared('db')\n#9 [internal function]: Phalcon\\Mvc\\Model\\Manager->_getConnection(Object(NovaMooc\\Models\\Users), Array)\n#10 [internal function]: Phalcon\\Mvc\\Model\\Manager->getReadConnection(Object(NovaMooc\\Models\\Users))\n#11 [internal function]: Phalcon\\Mvc\\Model->getReadConnection()\n#12 [internal function]: Phalcon\\Mvc\\Model\\MetaData\\Strategy\\Introspection->getMetaData(Object(NovaMooc\\Models\\Users), Object(Phalcon\\Di\\FactoryDefault))\n#13 [internal function]: Phalcon\\Mvc\\Model\\MetaData->initialize(Object(NovaMooc\\Models\\Users), 'novamooc\\\\models...', 'nov_users', 'public')\n#14 [internal function]: Phalcon\\Mvc\\Model\\MetaData->readMetaData(Object(NovaMooc\\Models\\Users))\n#15 [internal function]: Phalcon\\Mvc\\Model\\MetaData->hasAttribute(Object(NovaMooc\\Models\\Users), 'email')\n#16 [internal function]: Phalcon\\Mvc\\Model\\Query->_getQualified(Array)\n#17 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#18 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#19 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array)\n#20 [internal function]: Phalcon\\Mvc\\Model\\Query->_prepareSelect()\n#21 [internal function]: Phalcon\\Mvc\\Model\\Query->parse()\n#22 [internal function]: Phalcon\\Mvc\\Model\\Query->execute()\n#23 \/var\/www\/html\/app\/models\/Users.php(95): Phalcon\\Mvc\\Model::findFirst(Array)\n#24 \/var\/www\/html\/app\/controllers\/IndexController.php(32): NovaMooc\\Models\\Users::findFirst(Array)\n#25 [internal function]: IndexController->loginAction()\n#26 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(IndexController), 'loginAction', Array)\n#27 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#28 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/login')\n#29 {main}"}
[2020-03-15T16:54:18+00:00][error] {"message":"SQLSTATE[08006] [7] could not translate host name \"mooc-db\" to address: No address associated with hostname","trace":"#0 [internal function]: PDO->__construct('pgsql:host=mooc...', 'postgres', 'root', Array)\n#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->connect(Array)\n#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\Postgresql->connect(Array)\n#3 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->__construct(Array)\n#4 \/var\/www\/html\/app\/config\/services.php(82): Phalcon\\Db\\Adapter\\Pdo\\Postgresql->__construct(Array)\n#5 [internal function]: Closure->{closure}()\n#6 [internal function]: Phalcon\\Di\\Service->resolve(NULL, Object(Phalcon\\Di\\FactoryDefault))\n#7 [internal function]: Phalcon\\Di->get('db', NULL)\n#8 [internal function]: Phalcon\\Di->getShared('db')\n#9 [internal function]: Phalcon\\Mvc\\Model\\Manager->_getConnection(Object(NovaMooc\\Models\\Users), Array)\n#10 [internal function]: Phalcon\\Mvc\\Model\\Manager->getReadConnection(Object(NovaMooc\\Models\\Users))\n#11 [internal function]: Phalcon\\Mvc\\Model->getReadConnection()\n#12 [internal function]: Phalcon\\Mvc\\Model\\MetaData\\Strategy\\Introspection->getMetaData(Object(NovaMooc\\Models\\Users), Object(Phalcon\\Di\\FactoryDefault))\n#13 [internal function]: Phalcon\\Mvc\\Model\\MetaData->initialize(Object(NovaMooc\\Models\\Users), 'novamooc\\\\models...', 'nov_users', 'public')\n#14 [internal function]: Phalcon\\Mvc\\Model\\MetaData->readMetaData(Object(NovaMooc\\Models\\Users))\n#15 [internal function]: Phalcon\\Mvc\\Model\\MetaData->hasAttribute(Object(NovaMooc\\Models\\Users), 'email')\n#16 [internal function]: Phalcon\\Mvc\\Model\\Query->_getQualified(Array)\n#17 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#18 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#19 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array)\n#20 [internal function]: Phalcon\\Mvc\\Model\\Query->_prepareSelect()\n#21 [internal function]: Phalcon\\Mvc\\Model\\Query->parse()\n#22 [internal function]: Phalcon\\Mvc\\Model\\Query->execute()\n#23 \/var\/www\/html\/app\/models\/Users.php(95): Phalcon\\Mvc\\Model::findFirst(Array)\n#24 \/var\/www\/html\/app\/controllers\/IndexController.php(32): NovaMooc\\Models\\Users::findFirst(Array)\n#25 [internal function]: IndexController->loginAction()\n#26 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(IndexController), 'loginAction', Array)\n#27 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#28 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/login')\n#29 {main}"}
[2020-03-15T16:54:24+00:00][error] {"message":"SQLSTATE[08006] [7] could not translate host name \"mooc-db\" to address: No address associated with hostname","trace":"#0 [internal function]: PDO->__construct('pgsql:host=mooc...', 'postgres', 'root', Array)\n#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->connect(Array)\n#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\Postgresql->connect(Array)\n#3 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->__construct(Array)\n#4 \/var\/www\/html\/app\/config\/services.php(82): Phalcon\\Db\\Adapter\\Pdo\\Postgresql->__construct(Array)\n#5 [internal function]: Closure->{closure}()\n#6 [internal function]: Phalcon\\Di\\Service->resolve(NULL, Object(Phalcon\\Di\\FactoryDefault))\n#7 [internal function]: Phalcon\\Di->get('db', NULL)\n#8 [internal function]: Phalcon\\Di->getShared('db')\n#9 [internal function]: Phalcon\\Mvc\\Model\\Manager->_getConnection(Object(NovaMooc\\Models\\Users), Array)\n#10 [internal function]: Phalcon\\Mvc\\Model\\Manager->getReadConnection(Object(NovaMooc\\Models\\Users))\n#11 [internal function]: Phalcon\\Mvc\\Model->getReadConnection()\n#12 [internal function]: Phalcon\\Mvc\\Model\\MetaData\\Strategy\\Introspection->getMetaData(Object(NovaMooc\\Models\\Users), Object(Phalcon\\Di\\FactoryDefault))\n#13 [internal function]: Phalcon\\Mvc\\Model\\MetaData->initialize(Object(NovaMooc\\Models\\Users), 'novamooc\\\\models...', 'nov_users', 'public')\n#14 [internal function]: Phalcon\\Mvc\\Model\\MetaData->readMetaData(Object(NovaMooc\\Models\\Users))\n#15 [internal function]: Phalcon\\Mvc\\Model\\MetaData->hasAttribute(Object(NovaMooc\\Models\\Users), 'email')\n#16 [internal function]: Phalcon\\Mvc\\Model\\Query->_getQualified(Array)\n#17 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#18 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#19 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array)\n#20 [internal function]: Phalcon\\Mvc\\Model\\Query->_prepareSelect()\n#21 [internal function]: Phalcon\\Mvc\\Model\\Query->parse()\n#22 [internal function]: Phalcon\\Mvc\\Model\\Query->execute()\n#23 \/var\/www\/html\/app\/models\/Users.php(95): Phalcon\\Mvc\\Model::findFirst(Array)\n#24 \/var\/www\/html\/app\/controllers\/IndexController.php(32): NovaMooc\\Models\\Users::findFirst(Array)\n#25 [internal function]: IndexController->loginAction()\n#26 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(IndexController), 'loginAction', Array)\n#27 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#28 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/login')\n#29 {main}"}
[2020-03-15T16:54:25+00:00][error] {"message":"SQLSTATE[08006] [7] could not translate host name \"mooc-db\" to address: No address associated with hostname","trace":"#0 [internal function]: PDO->__construct('pgsql:host=mooc...', 'postgres', 'root', Array)\n#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->connect(Array)\n#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\Postgresql->connect(Array)\n#3 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->__construct(Array)\n#4 \/var\/www\/html\/app\/config\/services.php(82): Phalcon\\Db\\Adapter\\Pdo\\Postgresql->__construct(Array)\n#5 [internal function]: Closure->{closure}()\n#6 [internal function]: Phalcon\\Di\\Service->resolve(NULL, Object(Phalcon\\Di\\FactoryDefault))\n#7 [internal function]: Phalcon\\Di->get('db', NULL)\n#8 [internal function]: Phalcon\\Di->getShared('db')\n#9 [internal function]: Phalcon\\Mvc\\Model\\Manager->_getConnection(Object(NovaMooc\\Models\\Users), Array)\n#10 [internal function]: Phalcon\\Mvc\\Model\\Manager->getReadConnection(Object(NovaMooc\\Models\\Users))\n#11 [internal function]: Phalcon\\Mvc\\Model->getReadConnection()\n#12 [internal function]: Phalcon\\Mvc\\Model\\MetaData\\Strategy\\Introspection->getMetaData(Object(NovaMooc\\Models\\Users), Object(Phalcon\\Di\\FactoryDefault))\n#13 [internal function]: Phalcon\\Mvc\\Model\\MetaData->initialize(Object(NovaMooc\\Models\\Users), 'novamooc\\\\models...', 'nov_users', 'public')\n#14 [internal function]: Phalcon\\Mvc\\Model\\MetaData->readMetaData(Object(NovaMooc\\Models\\Users))\n#15 [internal function]: Phalcon\\Mvc\\Model\\MetaData->hasAttribute(Object(NovaMooc\\Models\\Users), 'email')\n#16 [internal function]: Phalcon\\Mvc\\Model\\Query->_getQualified(Array)\n#17 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#18 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#19 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array)\n#20 [internal function]: Phalcon\\Mvc\\Model\\Query->_prepareSelect()\n#21 [internal function]: Phalcon\\Mvc\\Model\\Query->parse()\n#22 [internal function]: Phalcon\\Mvc\\Model\\Query->execute()\n#23 \/var\/www\/html\/app\/models\/Users.php(95): Phalcon\\Mvc\\Model::findFirst(Array)\n#24 \/var\/www\/html\/app\/controllers\/IndexController.php(32): NovaMooc\\Models\\Users::findFirst(Array)\n#25 [internal function]: IndexController->loginAction()\n#26 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(IndexController), 'loginAction', Array)\n#27 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#28 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/login')\n#29 {main}"}
[2020-03-15T16:55:22+00:00][error] {"message":"SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"mooc-db\" (172.23.0.2) and accepting\n\tTCP\/IP connections on port 5432?","trace":"#0 [internal function]: PDO->__construct('pgsql:host=mooc...', 'postgres', 'root', Array)\n#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->connect(Array)\n#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\Postgresql->connect(Array)\n#3 [internal function]: Phalcon\\Db\\Adapter\\Pdo\\AbstractPdo->__construct(Array)\n#4 \/var\/www\/html\/app\/config\/services.php(82): Phalcon\\Db\\Adapter\\Pdo\\Postgresql->__construct(Array)\n#5 [internal function]: Closure->{closure}()\n#6 [internal function]: Phalcon\\Di\\Service->resolve(NULL, Object(Phalcon\\Di\\FactoryDefault))\n#7 [internal function]: Phalcon\\Di->get('db', NULL)\n#8 [internal function]: Phalcon\\Di->getShared('db')\n#9 [internal function]: Phalcon\\Mvc\\Model\\Manager->_getConnection(Object(NovaMooc\\Models\\Users), Array)\n#10 [internal function]: Phalcon\\Mvc\\Model\\Manager->getReadConnection(Object(NovaMooc\\Models\\Users))\n#11 [internal function]: Phalcon\\Mvc\\Model->getReadConnection()\n#12 [internal function]: Phalcon\\Mvc\\Model\\MetaData\\Strategy\\Introspection->getMetaData(Object(NovaMooc\\Models\\Users), Object(Phalcon\\Di\\FactoryDefault))\n#13 [internal function]: Phalcon\\Mvc\\Model\\MetaData->initialize(Object(NovaMooc\\Models\\Users), 'novamooc\\\\models...', 'nov_users', 'public')\n#14 [internal function]: Phalcon\\Mvc\\Model\\MetaData->readMetaData(Object(NovaMooc\\Models\\Users))\n#15 [internal function]: Phalcon\\Mvc\\Model\\MetaData->hasAttribute(Object(NovaMooc\\Models\\Users), 'email')\n#16 [internal function]: Phalcon\\Mvc\\Model\\Query->_getQualified(Array)\n#17 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#18 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#19 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array)\n#20 [internal function]: Phalcon\\Mvc\\Model\\Query->_prepareSelect()\n#21 [internal function]: Phalcon\\Mvc\\Model\\Query->parse()\n#22 [internal function]: Phalcon\\Mvc\\Model\\Query->execute()\n#23 \/var\/www\/html\/app\/models\/Users.php(95): Phalcon\\Mvc\\Model::findFirst(Array)\n#24 \/var\/www\/html\/app\/controllers\/IndexController.php(32): NovaMooc\\Models\\Users::findFirst(Array)\n#25 [internal function]: IndexController->loginAction()\n#26 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(IndexController), 'loginAction', Array)\n#27 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#28 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/login')\n#29 {main}"}
[2020-03-15T16:55:26+00:00][error] {"message":"User not found","trace":"#0 [internal function]: IndexController->loginAction()\n#1 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(IndexController), 'loginAction', Array)\n#2 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#3 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/login')\n#4 {main}"}
[2020-03-15T16:55:35+00:00][error] {"message":"User not found","trace":"#0 [internal function]: IndexController->loginAction()\n#1 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(IndexController), 'loginAction', Array)\n#2 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#3 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/login')\n#4 {main}"}
[2020-03-15T16:55:39+00:00][error] {"message":"User not found","trace":"#0 [internal function]: IndexController->loginAction()\n#1 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(IndexController), 'loginAction', Array)\n#2 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#3 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/login')\n#4 {main}"}
[2020-03-15T16:58:26+00:00][error] {"message":"ApiController handler class cannot be loaded","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->throwDispatchException('ApiController h...', 2)\n#1 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#2 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/course')\n#3 {main}"}
[2020-03-15T16:58:32+00:00][error] {"message":"ApiController handler class cannot be loaded","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->throwDispatchException('ApiController h...', 2)\n#1 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#2 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/courses')\n#3 {main}"}
[2020-03-15T16:58:56+00:00][error] {"message":"Requested claim is not configured","trace":"#0 \/var\/www\/html\/app\/plugins\/SecurityPlugin.php(119): Lcobucci\\JWT\\Token->getClaim('user_id')\n#1 \/var\/www\/html\/app\/config\/services.php(153): SecurityPlugin::getUserIdFromToken(Object(Phalcon\\Config), 'eyJ0eXAiOiJKV1Q...')\n#2 [internal function]: Closure->{closure}()\n#3 [internal function]: Phalcon\\Di\\Service->resolve(Array, Object(Phalcon\\Di\\FactoryDefault))\n#4 [internal function]: Phalcon\\Di->get('user', Array)\n#5 \/var\/www\/html\/app\/controllers\/UsersController.php(37): Phalcon\\Di->__call('getUser', Array)\n#6 [internal function]: UsersController->coursesAction()\n#7 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(UsersController), 'coursesAction', Array)\n#8 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#9 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/user\/cours...')\n#10 {main}"}
[2020-03-15T17:01:17+00:00][error] {"message":"Requested claim is not configured","trace":"#0 \/var\/www\/html\/app\/plugins\/SecurityPlugin.php(119): Lcobucci\\JWT\\Token->getClaim('user_id')\n#1 \/var\/www\/html\/app\/config\/services.php(153): SecurityPlugin::getUserIdFromToken(Object(Phalcon\\Config), 'eyJ0eXAiOiJKV1Q...')\n#2 [internal function]: Closure->{closure}()\n#3 [internal function]: Phalcon\\Di\\Service->resolve(Array, Object(Phalcon\\Di\\FactoryDefault))\n#4 [internal function]: Phalcon\\Di->get('user', Array)\n#5 \/var\/www\/html\/app\/controllers\/UsersController.php(37): Phalcon\\Di->__call('getUser', Array)\n#6 [internal function]: UsersController->coursesAction()\n#7 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(UsersController), 'coursesAction', Array)\n#8 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#9 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/user\/cours...')\n#10 {main}"}
[2020-03-15T17:03:07+00:00][error] {"message":"Column 'Users_id' doesn't belong to any of the selected models (1), when preparing: SELECT [NovaMooc\\Models\\Courses].* FROM [NovaMooc\\Models\\Courses] WHERE [Users_id] = :APR0:","trace":"#0 [internal function]: Phalcon\\Mvc\\Model\\Query->_getQualified(Array)\n#1 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array, true)\n#2 [internal function]: Phalcon\\Mvc\\Model\\Query->_getExpression(Array)\n#3 [internal function]: Phalcon\\Mvc\\Model\\Query->_prepareSelect()\n#4 [internal function]: Phalcon\\Mvc\\Model\\Query->parse()\n#5 [internal function]: Phalcon\\Mvc\\Model\\Query->execute()\n#6 \/var\/www\/html\/app\/models\/Courses.php(47): Phalcon\\Mvc\\Model::find(Array)\n#7 [internal function]: NovaMooc\\Models\\Courses::find(Array)\n#8 [internal function]: Phalcon\\Mvc\\Model\\Manager->getRelationRecords(Object(Phalcon\\Mvc\\Model\\Relation), Object(NovaMooc\\Models\\Users), NULL)\n#9 [internal function]: Phalcon\\Mvc\\Model->getRelated('courses')\n#10 \/var\/www\/html\/app\/controllers\/UsersController.php(40): Phalcon\\Mvc\\Model->__get('courses')\n#11 [internal function]: UsersController->coursesAction()\n#12 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->callActionMethod(Object(UsersController), 'coursesAction', Array)\n#13 [internal function]: Phalcon\\Dispatcher\\AbstractDispatcher->dispatch()\n#14 \/var\/www\/html\/public\/index.php(47): Phalcon\\Mvc\\Application->handle('\/api\/user\/cours...')\n#15 {main}"}
